<?php

declare(strict_types=1);

/**
 * @file
 * Provides a product entity type.
 */

use Drupal\Core\Entity\EntityStorageException;
use Drupal\Core\Render\Element;
use Drupal\user\UserInterface;
use Drupal\webform\Entity\Webform;
use Drupal\webform\Entity\WebformSubmission;
use Drupal\webform\WebformInterface;

/**
 * Implements hook_theme().
 */
function odt_core_theme(): array {
  return [
    'odt_core_product' => ['render element' => 'elements'],
  ];
}

/**
 * Prepares variables for product templates.
 *
 * Default template: odt-core-product.html.twig.
 *
 * @param array $variables
 *   An associative array containing:
 *   - elements: An associative array containing the product information and any
 *     fields attached to the entity.
 *   - attributes: HTML attributes for the containing element.
 */
function template_preprocess_odt_core_product(array &$variables): void {
  $variables['view_mode'] = $variables['elements']['#view_mode'];
  foreach (Element::children($variables['elements']) as $key) {
    $variables['content'][$key] = $variables['elements'][$key];
  }
}

/**
 * Implements hook_user_cancel().
 */
function odt_core_user_cancel($edit, UserInterface $account, $method): void {
  switch ($method) {
    case 'user_cancel_block_unpublish':
      // Unpublish products.
      $storage = \Drupal::entityTypeManager()->getStorage('odt_core_product');
      $odt_core_product_ids = $storage->getQuery()
        ->condition('uid', $account->id())
        ->condition('status', 1)
        ->accessCheck(FALSE)
        ->execute();
      foreach ($storage->loadMultiple($odt_core_product_ids) as $odt_core_product) {
        $odt_core_product->set('status', FALSE)->save();
      }
      break;

    case 'user_cancel_reassign':
      // Anonymize products.
      $storage = \Drupal::entityTypeManager()->getStorage('odt_core_product');
      $odt_core_product_ids = $storage->getQuery()
        ->condition('uid', $account->id())
        ->accessCheck(FALSE)
        ->execute();
      foreach ($storage->loadMultiple($odt_core_product_ids) as $odt_core_product) {
        $odt_core_product->setOwnerId(0)->save();
      }
      break;
  }
}

/**
 * Implements hook_ENTITY_TYPE_predelete() for user entities.
 */
function odt_core_user_predelete(UserInterface $account): void {
  // Delete products that belong to this account.
  $storage = \Drupal::entityTypeManager()->getStorage('odt_core_product');
  $odt_core_product_ids = $storage->getQuery()
    ->condition('uid', $account->id())
    ->accessCheck(FALSE)
    ->execute();
  $storage->delete(
    $storage->loadMultiple($odt_core_product_ids)
  );
}

/**
 * Creates product_featured_notification webform submission.
 * @return void
 * @throws EntityStorageException
 */
function product_featured_notification(): void {
  // Todo: collect product_featured summary.
  $webform_id = 'product_featured_notification';
  $webform = Webform::load($webform_id);
  if ($webform instanceof WebformInterface) {
    $webform_submission = WebformSubmission::create([
      'webform_id' => $webform_id,
      'data' => [
        'products_summary' => [
          [
            'product' => 'ABC',
            'cta_clicks' => 5,
          ],
          [
            'product' => 'DEF',
            'cta_clicks' => 10,
          ],
        ],
      ],
    ]);
    // Save the submission.
    $webform_submission->save();
  }
}
